---
name: ci-cargo-casper

on:
  push:
    branches:
      - "main"
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - "main"
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain from file
        id: nightly-toolchain
        run: echo "::set-output name=version::$(cat resources/rust-toolchain.in)"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.nightly-toolchain.outputs.version }}
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: fmt --all -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: audit

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: clippy --workspace --all-targets -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: test --workspace
