---
name: publish-cargo-casper

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Publish Lib
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: publish --package cargo-casper-lib --token ${{ secrets.crates_io_token }}

      - name: Publish Bin
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: publish --package cargo-casper --token ${{ secrets.crates_io_token }}
